# Shell
source $HOME/.dotfiles/shell/autocompletion
source $HOME/.dotfiles/shell/general
source $HOME/.dotfiles/shell/git
source $HOME/.dotfiles/shell/history
source $HOME/.dotfiles/shell/homebrew
source $HOME/.dotfiles/shell/hooks
source $HOME/.dotfiles/shell/media
source $HOME/.dotfiles/shell/prompt
source $HOME/.dotfiles/shell/rails
source $HOME/.dotfiles/shell/rbenv
source $HOME/.dotfiles/shell/rspec
source $HOME/.dotfiles/shell/ruby
source $HOME/.dotfiles/shell/shell

# Paths
export PATH="/opt/homebrew/sbin:/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/python@3.12/libexec/bin:$PATH"
export PATH="$PATH:$HOME/.dotfiles/bin"
export PATH="$PATH:$HOME/.dotfiles/git/bin"
export PATH="$PATH:$HOME/.dotfiles/macos/bin"
export PATH="$PATH:$HOME/Code/filing/filing/bin"
export PATH="$PATH:$HOME/.go/bin"

# Local bin directory takes highest precedence
# Being careful as to when a bin directory is around I don't know the contents of ;)
export PATH="bin:$PATH"

[ -s ~/.zshrc.local ] && source ~/.zshrc.local
