require: rubocop-rspec

# Mostly following https://robots.thoughtbot.com/lets-not
# which increases example length.
RSpec/ExampleLength:
  Enabled: false

# I may have PDF or otherwise graphics related specs
# that combine many expectations in one spec for rendering convenience.
RSpec/MultipleExpectations:
  Enabled: false

# For robustness and clarity, we don't guess the spec type from the folder path.
# The default is activated in RSpec and once deactivated, we need to deactivate the cop as well.
RSpec/Rails/InferredSpecType:
  Enabled: false
