add_newline = true
command_timeout = 200
format = "[$username]($username_style)[$directory$git_branch]($style)$character"

[character]
error_symbol = "[×](bold red)"
success_symbol = "[❯](bold #FFAB91)[❯](bold #FFAB91)[❯](bold #FFAB91)"

[directory]
style = "bold yellow"
read_only = 'READ ONLY YA'
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold yellow"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "bold"

[username]
format = '[$user]($style)' # Default: '[$user]($style) in '
disabled = false
style_root = 'bold cyan'
show_always = true
aliases = { "admin" = "ADMIN ", "orange" = "" }
