# Copy user pictures generated by sphere to privileged default location
sudo cp -R $HOME/Library/User\ Pictures/Unicolor /Library/User\ Pictures &> /dev/null

if [ -f "/Library/User Pictures/Unicolor/$USER.png" ]; then
  # This user has a user picture, apply it
  sudo dscl . -delete /users/$USER Picture
  sudo dscl . -delete /users/$USER JPEGPhoto
  sudo dscl . create /Users/$USER Picture "/Library/User Pictures/Unicolor/$USER.png"
fi

# This is the last file in this directory, exit with status 0
ls /tmp > /dev/null

