[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
size = 12

[window]
padding.x = 14
padding.y = 14
# Cannot use "Both" because that breaks alt+number keys such as |
option_as_alt = 'OnlyRight'

[keyboard]
bindings = [
  { mods = "Command", key = "Comma", command = { program = '/usr/bin/open', args = ["/Users/orange/.config/alacritty/alacritty.toml"] } },
  { mods = "Command|Shift", key = "K", action = "ClearHistory" },
  { mods = "Command|Shift", key = "E", command = "/Users/orange/.config/alacritty/reset" },
  { mods = "Command", key = "N", action = "CreateNewWindow" },
  { mods = "Shift", key = "Return", chars = "\n" }, # Multi-line TUI inputs, like in OpenCode
  { key = "Left", mods = "Command|Alt", action = "SelectPreviousTab" },
  { key = "Right", mods = "Command|Alt", action = "SelectNextTab" },
  { key = "NumpadEnter", chars = "\r" }
 ]

[[hints.enabled]]
# (\\./|/)     Starts with "./" or "/"
# [^\\s]*      Any non-whitespace characters
regex = "(\\./|/|[a-z0-9]+/|https?://|~/)[^\\s]*"
command = { program = "/Users/orange/.dotfiles/bin/openuri" }
mouse = { enabled = true, mods = "Command" }
